### ISSUE TITLE
Yoast Search Console:  Fatal Error 'Yoast_Google_WPCache' not found

### ISSUE THREAD

**Issue by yogabearpc** [Yoast/api-libs#29]
Hi all,

Yesterday my Yoast Search Console was working fine.  Now when I click on it I get the following error on a blank white page

Fatal error: Class 'Yoast_Google_WPCache' not found in /home/yogabearcomputers/www.yogabearpc.com/wp-content/plugins/wordpress-seo/vendor/yoast/api-libs/google/Google_Client.php on line 90

Anyone have any ideas?  Thanks

**Comment by Rarst** [comment]
No changes / updates at all?

Could you please check if class file properly exist and in place at `...\plugins\wordpress-seo\vendor\yoast\api-libs\google\cache\Google_WPCache.php` ?

**Comment by masonjames** [comment]
We also encountered this while working on a development environment (on Pantheon).

It doesn't happen on production (which is an identical copy) and I've confirmed the actual file exists. FWIW we're using the premium version of Yoast SEO in this case.  Let me know if there's something else we could provide to help with debugging.  For now we've disabled the plugin in the dev environment.

**Comment by prh-developer** [comment]
Same problem but working on a WP Stagecoach dev environment

**Comment by explorier** [comment]
I'm getting this issue on all environments (dev, test, and live) on a Pantheon site. We are using WordPress 4.9.6. Has anyone found any causes of this error?
`
Fatal error: Uncaught Error: Class 'Yoast_Google_WPCache' not found in /srv/bindings/5feb47fad51b40bf93fad54a9ab1c92d/code/wp-content/plugins/wordpress-seo/vendor/yoast/api-libs/google/Google_Client.php:90 Stack trace: #0 /srv/bindings/5feb47fad51b40bf93fad54a9ab1c92d/code/wp-content/plugins/wordpress-seo/vendor/yoast/api-libs/class-api-google-client.php(36): Yoast_Google_Client->__construct() #1 /srv/bindings/5feb47fad51b40bf93fad54a9ab1c92d/code/wp-content/plugins/wordpress-seo/admin/google_search_console/class-gsc-service.php(162): Yoast_Api_Google_Client->__construct(Array, 'wpseo-gsc', 'https://www.goo...') #2 /srv/bindings/5feb47fad51b40bf93fad54a9ab1c92d/code/wp-content/plugins/wordpress-seo/admin/google_search_console/class-gsc-service.php(31): WPSEO_GSC_Service->set_client() #3 /srv/bindings/5feb47fad51b40bf93fad54a9ab1c92d/code/wp-content/plugins/wordpress-seo/admin/google_search_console/class-gsc.php(275): WPSEO_GSC_Service->__construct('') #4 /srv/bindings/5feb47fad51b40bf93fad54a9ab1c92d/code/wp-content/plugi in /srv/bindings/5feb47fad51b40bf93fad54a9ab1c92d/code/wp-content/plugins/wordpress-seo/vendor/yoast/api-libs/google/Google_Client.php on line 90`

Edit: I realized this was the same issue mentioned in https://github.com/Yoast/api-libs/issues/21 and fixed with this command:

`git add -f wp-content/plugins/wordpress-seo/vendor/yoast/api-libs/google/cache`
